### ISSUE TITLE
Revise Styling

### ISSUE THREAD

**Issue by juliabellmann** [juliabellmann/workflow-wizard#18]
## Value proposition
As a user
I want to see an optical modern task list
In order to want to use it frequently
## Description

![Image](https://github.com/user-attachments/assets/9b50a2c2-b1ae-4fde-9af2-0d8104e4f01b)

## Acceptance criteria
- [ ] modern colors
- [ ] simple but with visual highlights
- [ ] modern icons
- [ ] mordern font
## Tasks
- [ ] add color theme at :root
- [ ] add responsive design for SE and desktop
- [ ] change some icons
- [ ] add favicon
- [ ] change font
- [ ] add logo
