### ISSUE TITLE
Task Details ✔

### ISSUE THREAD

**Issue by juliabellmann** [juliabellmann/workflow-wizard#3]
# Task Details

## Value Proposition

**As a user**

**I want to** access detailed information about each task,

**so that** I can understand the requirements and context better.

## Description

![Image](https://github.com/user-attachments/assets/3ecaed10-0716-471f-ade1-45a46167b038)

## Acceptance Criteria

- Each task in the task list has a link to a details page.
- Each details page contains:
  - Task title
  - Task description
  - Due date
  - Priority level
- The detailed view includes a “back” link, allowing users to easily navigate back to the list of tasks.

## Tasks

- [ ] Create feature branch `feature/task-details`
- [ ] Add Details Button to the TaskCard
- [ ] Create Task Details Page
- [ ] Add informations to the Task Details page
- [ ] Add the "back" button
- [ ] Link the pages
