### ISSUE TITLE
Update Task ✔

### ISSUE THREAD

**Issue by juliabellmann** [juliabellmann/workflow-wizard#6]
# Update Task

## Value Proposition

**As a user**

**I want to** update the details of existing tasks,

**so that** they reflect the most accurate and relevant information.

## Description

![Image](https://github.com/user-attachments/assets/f6a220cf-79c6-4814-bf1d-c346e2426ac7)

## Acceptance Criteria

- Each task details page includes an easily accessible edit option.
- Clicking the edit option opens a new page with a form pre-filled with the task’s existing details for modification.
- The form allows for edits to all task details, including:
  - Task title
  - Task description
  - Due date
  - Priority level
- The following fields are mandatory:
  - Task title
  - Due date
  - Priority level
- The form section includes options for both saving and cancelling the action.
- The cancellation option allows the user to back out of the edit process if selected by mistake or if they change their mind.
- Submissions with empty required fields are blocked, with validation messages indicating the missing required fields.
- Upon confirming the save, the user is immediately redirected to the details page of the edited task, and the changes are saved and reflected.

## Tasks

- [ ] Create feature branch `feature/update-task`
- [ ] create new component for update-form
- [ ] add new page for edit form
- [ ] add transfer function of existing informations
- [ ] add update and cancel funtions
- [ ] take over required informations
- [ ] connect redirection to details page after confirm the edit
