### ISSUE TITLE
Mark Task as Completed

### ISSUE THREAD

**Issue by juliabellmann** [juliabellmann/workflow-wizard#7]
# Mark Task as Completed

## Value Proposition

**As a user**

**I want to** mark tasks as completed,

**so that** I can keep track of which tasks have been finished and which are still pending.

## Description

![Image](https://github.com/user-attachments/assets/5e262a5f-0e5a-405b-97ce-8dc41f43c8e8)

## Acceptance Criteria

- Each task includes a checkbox to mark the task as completed, available in both the task list and the task detail page.
- When a task is marked as completed, it is moved to a separate “Completed Tasks” section below the task list.
- The “Completed Tasks” section displays completed tasks with a clear visual distinction (e.g., with a strikethrough or a different colour).
- Users can undo the completion status by clicking the checkbox again, moving the task back to the task list.
- If all tasks in the tasks list are marked as completed, a message is displayed indicating that all tasks have been completed.

## Tasks

- [ ] Create feature branch `feature/mark-task-completed`
- [ ] add component for checkbox -> Mark Task As Done
- [ ] add toggle funktion for checkbox
- [ ] add sort function for done tasks
- [ ] add information massage, if every task is marked as done
- [ ] add clear visual distinction
